//
// Created by mikef on 09/11/2023.
//

#ifndef MURILLO_MAURICIO_EXAMENCPP_OPERACIONES_BASICAS_H
#define MURILLO_MAURICIO_EXAMENCPP_OPERACIONES_BASICAS_H


class Operaciones_Basicas {

};


#endif //MURILLO_MAURICIO_EXAMENCPP_OPERACIONES_BASICAS_H
