//
// Created by mikef on 09/11/2023.
//

#ifndef MURILLO_MAURICIO_EXAMENCPP_PARTE_3_1_H
#define MURILLO_MAURICIO_EXAMENCPP_PARTE_3_1_H


class Parte_3_1 {

};


#endif //MURILLO_MAURICIO_EXAMENCPP_PARTE_3_1_H
